<div class="gc-module gc-workspace" data-gc-workspace="1" data-status-url="{$status_url|default:''|escape:'html'}">
<div class="gc-heading"><h2>{$title|default:'Mi cartera'|escape:'html'}</h2><span class="gc-agent">{$agent.name|default:''|escape:'html'} · {$agent.extension|default:''|escape:'html'}</span></div>
{if $message|default:''}<div class="gc-alert gc-alert-info">{$message|escape:'html'}</div>{/if}{if !$agent.mapped|default:1}<div class="gc-alert gc-alert-error">{$label_unmapped|default:'Su usuario no tiene un agente y extensión válidos asignados.'|escape:'html'}</div>{/if}
{if $client|default:array()}<section class="gc-card"><div class="gc-heading"><div><h3>{$client.name|default:'Sin nombre'|escape:'html'}</h3><small>{$label_client_id|default:'Cliente'|escape:'html'}: {$client.external_id|default:$client.id|default:''|escape:'html'}</small></div><span class="gc-badge">{$client.state_label|default:$client.state|default:''|escape:'html'}</span></div>
<dl class="gc-details">{foreach from=$client.fields|default:array() key=key item=value}<dt>{$key|escape:'html'}</dt><dd>{$value|escape:'html'}</dd>{/foreach}</dl>
<form method="post" action="{$start_call_url|default:''|escape:'html'}" class="gc-call-form" data-gc-call-form="1"><input type="hidden" name="csrf_token" value="{$csrf_token|default:''|escape:'html'}" /><input type="hidden" name="client_id" value="{$client.id|default:''|escape:'html'}" /><input type="hidden" name="claim_token" value="{$client.claim_token|default:''|escape:'html'}" /><input type="hidden" name="idempotency_key" value="{$call_idempotency_key|default:''|escape:'html'}" />
<label>{$label_phone|default:'Teléfono'|escape:'html'} <select name="phone_id" required="required">{foreach from=$client.phones|default:array() item=p}<option value="{$p.id|default:''|escape:'html'}"{if !$p.usable|default:1} disabled="disabled"{/if}>{$p.label|default:'Teléfono'|escape:'html'}: {$p.masked|default:$p.number|default:''|escape:'html'}</option>{/foreach}</select></label><button class="gc-call" type="submit"{if !$can_call|default:1} disabled="disabled"{/if}>{$label_call|default:'Llamar'|escape:'html'}</button><span class="gc-call-status" aria-live="polite"></span></form>
<form method="post" action="{$save_outcome_url|default:''|escape:'html'}" class="gc-form gc-outcome-form" data-gc-outcome-form="1"><input type="hidden" name="csrf_token" value="{$csrf_token|default:''|escape:'html'}" /><input type="hidden" name="client_id" value="{$client.id|default:''|escape:'html'}" /><input type="hidden" name="attempt_id" value="{$attempt.id|default:''|escape:'html'}" /><input type="hidden" name="idempotency_key" value="{$outcome_idempotency_key|default:''|escape:'html'}" />
<label>{$label_outcome|default:'Resultado'|escape:'html'} <select name="outcome_id" required="required" data-gc-outcome="1"><option value="">{$label_select|default:'Seleccione…'|escape:'html'}</option>{foreach from=$outcomes|default:array() item=o}<option value="{$o.id|default:''|escape:'html'}" data-callback="{$o.requires_callback|default:0|escape:'html'}">{$o.label|default:$o.code|default:''|escape:'html'}</option>{/foreach}</select></label>
<div class="gc-callback-fields" data-gc-callback-fields="1"><label>{$label_callback_at|default:'Fecha y hora del callback'|escape:'html'} <input type="text" name="callback_at" placeholder="AAAA-MM-DD HH:MM" /></label><label>{$label_timezone|default:'Zona horaria'|escape:'html'} <input type="text" name="callback_timezone" value="{$campaign.timezone|default:'America/Guayaquil'|escape:'html'}" /></label></div>
<label>{$label_note|default:'Nota'|escape:'html'} <textarea name="note" rows="3" maxlength="2000">{$attempt.note|default:''|escape:'html'}</textarea></label><button type="submit"{if !$can_disposition|default:1} disabled="disabled"{/if}>{$label_save_and_next|default:'Guardar y continuar'|escape:'html'}</button></form></section>
{else}<div class="gc-empty gc-card"><p>{$label_no_client|default:'No tiene un cliente activo.'|escape:'html'}</p><form method="post" action="{$claim_url|default:''|escape:'html'}"><input type="hidden" name="csrf_token" value="{$csrf_token|default:''|escape:'html'}" /><input type="hidden" name="idempotency_key" value="{$claim_idempotency_key|default:''|escape:'html'}" /><button type="submit"{if !$agent.mapped|default:1} disabled="disabled"{/if}>{$label_claim|default:'Tomar siguiente cliente'|escape:'html'}</button></form></div>{/if}</div>
