<div class="gc-module gc-workspace" data-gc-workspace="1" data-status-url="{$status_url|default:''|escape:'html'}" data-attempt-id="{$attempt.id|default:''|escape:'html'}" data-gc-outcome-required="{$outcome_required|default:0|escape:'html'}">
<div class="gc-heading"><h2>{$title|default:'Mi cartera'|escape:'html'}</h2><span class="gc-agent">{$agent.name|default:''|escape:'html'}{if $agent.number|default:''} · {$agent.number|escape:'html'}{/if}</span></div>
{if $message|default:''}<div class="gc-alert gc-alert-info">{$message|escape:'html'}</div>{/if}{if !$agent.mapped|default:1}<div class="gc-alert gc-alert-error">{$label_unmapped|default:'Su usuario no tiene un agente y extensión válidos asignados.'|escape:'html'}</div>{/if}
<section class="gc-seat-panel{if $selected_seat|default:false} gc-seat-selected{/if}" aria-labelledby="gc-seat-title">
<div class="gc-seat-copy"><h3 id="gc-seat-title">{$label_seat_title|default:'Extensión de esta sesión'|escape:'html'}</h3>
{if $selected_seat|default:false}<p><span class="gc-seat-indicator" aria-hidden="true"></span>{$label_current_seat|default:'Extensión activa'|escape:'html'}: <strong>{$selected_seat.label|default:$selected_seat.sip_extension|default:$selected_seat.extension|default:''|escape:'html'}</strong>{if $selected_seat.label|default:'' && $selected_seat.sip_extension|default:$selected_seat.extension|default:''} <small>({$selected_seat.sip_extension|default:$selected_seat.extension|default:''|escape:'html'})</small>{/if}</p><p class="gc-seat-help">{$label_seat_session_help|default:'Las llamadas de esta sesión sonarán primero en esta extensión. Su cartera y estadísticas siguen asociadas a su usuario.'|escape:'html'}</p>
{else}<p class="gc-seat-warning">{$label_seat_required|default:'Seleccione la extensión del puesto donde está trabajando antes de llamar.'|escape:'html'}</p>{/if}</div>
<div class="gc-seat-controls">
<form method="post" action="{$seat_select_url|default:''|escape:'html'}" class="gc-seat-form"><input type="hidden" name="csrf_token" value="{$csrf_token|default:''|escape:'html'}" /><input type="hidden" name="idempotency_key" value="{$seat_idempotency_key|default:''|escape:'html'}" />
<label for="gc-seat-extension">{if $selected_seat|default:false}{$label_change_seat|default:'Cambiar extensión'|escape:'html'}{else}{$label_choose_seat|default:'Extensión disponible'|escape:'html'}{/if}</label><select id="gc-seat-extension" name="sip_extension" required="required"><option value="">{$label_select|default:'Seleccione…'|escape:'html'}</option>{foreach from=$seats|default:array() item=seat}<option value="{$seat.sip_extension|default:$seat.extension|default:''|escape:'html'}"{if $selected_seat|default:false && $selected_seat.sip_extension|default:$selected_seat.extension|default:'' == $seat.sip_extension|default:$seat.extension|default:''} selected="selected"{/if}>{$seat.label|default:$seat.sip_extension|default:$seat.extension|default:''|escape:'html'}{if $seat.label|default:'' && $seat.sip_extension|default:$seat.extension|default:''} ({$seat.sip_extension|default:$seat.extension|default:''|escape:'html'}){/if}</option>{foreachelse}<option value="" disabled="disabled">{$label_no_seats|default:'No hay extensiones disponibles'|escape:'html'}</option>{/foreach}</select><button type="submit"{if !$seats|default:array()} disabled="disabled"{/if}>{if $selected_seat|default:false}{$label_change|default:'Cambiar'|escape:'html'}{else}{$label_use_seat|default:'Usar extensión'|escape:'html'}{/if}</button></form>
{if $selected_seat|default:false}<form method="post" action="{$seat_release_url|default:''|escape:'html'}" class="gc-seat-release"><input type="hidden" name="csrf_token" value="{$csrf_token|default:''|escape:'html'}" /><input type="hidden" name="idempotency_key" value="{$seat_release_idempotency_key|default:''|escape:'html'}" /><button type="submit" class="gc-button-secondary">{$label_release_seat|default:'Liberar extensión'|escape:'html'}</button></form>{/if}</div>
</section>
{if $attempt_active|default:0}<div class="gc-alert gc-alert-info" role="status">{$label_active_attempt|default:'Hay una llamada activa. Espere a que finalice antes de iniciar otra.'|escape:'html'}</div>{/if}
{if $outcome_required|default:0}<div class="gc-alert gc-alert-error" role="alert">{$label_outcome_required|default:'Debe guardar el resultado de la llamada anterior antes de iniciar otra o salir de esta página.'|escape:'html'}</div>{/if}
{if $client|default:array()}<section class="gc-card gc-client-card"><header class="gc-client-header"><div class="gc-client-title"><span class="gc-eyebrow">{$label_current_client|default:'Cliente actual'|escape:'html'}</span><h3>{$client.name|default:'Sin nombre'|escape:'html'}</h3><span class="gc-client-id">{$label_client_id|default:'Cliente'|escape:'html'}: {$client.external_id|default:$client.id|default:''|escape:'html'}</span></div><div class="gc-client-header-meta"><span class="gc-badge">{$client.state_label|default:$client.state|default:''|escape:'html'}</span>{if $selected_seat|default:false}<span class="gc-extension-chip"><small>{$label_call_from|default:'Llamar desde'|escape:'html'}</small><strong>{$selected_seat.sip_extension|default:$selected_seat.extension|default:''|escape:'html'}</strong></span>{/if}</div></header>
<div class="gc-client-layout"><section class="gc-client-data" aria-labelledby="gc-client-data-title"><h4 id="gc-client-data-title">{$label_client_data|default:'Datos del cliente'|escape:'html'}</h4><dl class="gc-details">{foreach from=$client.fields|default:array() key=key item=value}<dt>{$key|escape:'html'}</dt><dd>{$value|escape:'html'}</dd>{foreachelse}<dt class="gc-visually-hidden">{$label_information|default:'Información'|escape:'html'}</dt><dd class="gc-muted">{$label_no_additional_data|default:'Sin datos adicionales.'|escape:'html'}</dd>{/foreach}</dl></section>
<section class="gc-phone-section" aria-labelledby="gc-phone-title"><div class="gc-phone-heading"><div><span class="gc-eyebrow">{$label_contact_numbers|default:'Números de contacto'|escape:'html'}</span><h4 id="gc-phone-title">{$label_choose_phone|default:'¿A qué número desea llamar?'|escape:'html'}</h4></div><span class="gc-phone-count">{$client.phones|default:array()|@count} {$label_numbers|default:'número(s)'|escape:'html'}</span></div>
<div class="gc-phone-list">{foreach from=$client.phones|default:array() item=p}<article class="gc-phone-card{if !$p.usable|default:1} gc-phone-unavailable{/if}" data-gc-phone-card="1" data-phone-id="{$p.id|default:''|escape:'html'}"><div class="gc-phone-main"><span class="gc-phone-icon" aria-hidden="true">☎</span><div><span class="gc-phone-type">{$p.label|default:'Teléfono'|escape:'html'}</span><strong class="gc-phone-number">{$p.masked|default:$p.number|default:''|escape:'html'}</strong></div></div><div class="gc-phone-facts"><span class="gc-phone-state">{if $p.state|default:'' == 'AVAILABLE'}Disponible{elseif $p.state|default:'' == 'ATTEMPTED'}Intentado{elseif $p.state|default:'' == 'ANSWERED'}Contestado{elseif $p.state|default:'' == 'NO_ANSWER'}Sin respuesta{elseif $p.state|default:'' == 'INVALID'}Inválido{elseif $p.state|default:'' == 'DO_NOT_CALL'}No llamar{else}{$p.state|default:'Disponible'|escape:'html'}{/if}</span><span><strong>{$p.attempt_count|default:0|escape:'html'}</strong> {$label_attempts|default:'intento(s)'|escape:'html'}</span><span>{if $p.last_call_at|default:''}{$label_last_call|default:'Última llamada'|escape:'html'}: <strong>{$p.last_call_at|escape:'html'}</strong>{else}{$label_never_called|default:'Sin llamadas previas'|escape:'html'}{/if}</span>{if $p.last_business_outcome_label|default:''}<span>{$label_last_result|default:'Último resultado'|escape:'html'}: <strong>{$p.last_business_outcome_label|escape:'html'}</strong></span>{/if}</div>
<form method="post" action="{$start_call_url|default:''|escape:'html'}" class="gc-phone-call-form" data-gc-call-form="1"><input type="hidden" name="csrf_token" value="{$csrf_token|default:''|escape:'html'}" /><input type="hidden" name="client_id" value="{$client.id|default:''|escape:'html'}" /><input type="hidden" name="phone_id" value="{$p.id|default:''|escape:'html'}" /><input type="hidden" name="claim_token" value="{$client.claim_token|default:''|escape:'html'}" /><input type="hidden" name="idempotency_key" value="{$call_idempotency_key|default:''|escape:'html'}-{$p.id|default:''|escape:'html'}" /><button class="gc-call" type="submit"{if !$p.usable|default:1} disabled="disabled" title="{$label_phone_unavailable|default:'Este número no está disponible para llamadas.'|escape:'html'}"{elseif !$selected_seat|default:false} disabled="disabled" title="{$label_seat_required|default:'Seleccione una extensión antes de llamar.'|escape:'html'}"{elseif !$can_call|default:1} disabled="disabled"{/if}><span aria-hidden="true">☎</span> {if $p.usable|default:1}{$label_call|default:'Llamar'|escape:'html'}{else}{$label_unavailable|default:'No disponible'|escape:'html'}{/if}</button><span class="gc-call-status" aria-live="polite">{if !$selected_seat|default:false}{$label_seat_required_short|default:'Seleccione una extensión.'|escape:'html'}{elseif $attempt_active|default:0}{$label_active_attempt_short|default:'Llamada en curso.'|escape:'html'}{elseif $outcome_required|default:0}{$label_outcome_required_short|default:'Guarde el resultado pendiente.'|escape:'html'}{/if}</span></form></article>{foreachelse}<div class="gc-alert gc-alert-error">{$label_no_phones|default:'Este cliente no tiene números disponibles.'|escape:'html'}</div>{/foreach}</div></section></div>
<form method="post" action="{$save_outcome_url|default:''|escape:'html'}" class="gc-form gc-outcome-form" data-gc-outcome-form="1"><input type="hidden" name="csrf_token" value="{$csrf_token|default:''|escape:'html'}" /><input type="hidden" name="client_id" value="{$client.id|default:''|escape:'html'}" /><input type="hidden" name="attempt_id" value="{$attempt.id|default:''|escape:'html'}" /><input type="hidden" name="idempotency_key" value="{$outcome_idempotency_key|default:''|escape:'html'}" />
<label>{$label_outcome|default:'Resultado'|escape:'html'} <select name="outcome_id" required="required" data-gc-outcome="1"><option value="">{$label_select|default:'Seleccione…'|escape:'html'}</option>{foreach from=$outcomes|default:array() item=o}<option value="{$o.id|default:''|escape:'html'}" data-callback="{$o.requires_callback|default:0|escape:'html'}">{$o.label|default:$o.code|default:''|escape:'html'}</option>{/foreach}</select></label>
<div class="gc-callback-fields" data-gc-callback-fields="1"><label>{$label_callback_at|default:'Fecha y hora del callback'|escape:'html'} <input type="text" name="callback_at" placeholder="AAAA-MM-DD HH:MM" /></label><label>{$label_timezone|default:'Zona horaria'|escape:'html'} <input type="text" name="callback_timezone" value="{$campaign.timezone|default:'America/Guayaquil'|escape:'html'}" /></label></div>
<label>{$label_note|default:'Nota'|escape:'html'} <textarea name="note" rows="3" maxlength="2000">{$attempt.note|default:''|escape:'html'}</textarea></label><button type="submit"{if !$can_disposition|default:1} disabled="disabled"{/if}>{$label_save_and_next|default:'Guardar y continuar'|escape:'html'}</button></form></section>
{else}<div class="gc-empty gc-card"><p>{$label_no_client|default:'No tiene un cliente activo.'|escape:'html'}</p><form method="post" action="{$claim_url|default:''|escape:'html'}"><input type="hidden" name="csrf_token" value="{$csrf_token|default:''|escape:'html'}" /><input type="hidden" name="idempotency_key" value="{$claim_idempotency_key|default:''|escape:'html'}" /><button type="submit"{if !$agent.mapped|default:1} disabled="disabled"{/if}>{$label_claim|default:'Tomar siguiente cliente'|escape:'html'}</button></form></div>{/if}</div>
